### ISSUE TITLE
Returns true for requited custom fields that are selects, even if the user has not selected anything.

### ISSUE THREAD

**Issue by travislima** [strangerstudios/pmpro-register-helper#120]
Returns true for requited custom fields that are selects, even if the user has not selected anything. This means they pass verification even if empty because using isset only tests the existence, not if that value is an empty string.

line 629 fix:
if(!empty($field->required) && (!isset( $_REQUEST[$field->name]) || (empty($_REQUEST[$field->name])) ))

By checking for 'empty', it also forces required selects to be false if the user has not selected anything and the value is an empty string.

**Comment by dparker1005** [comment]
Hi @travislima,

This change has released in PMPro Register Helper v1.3.7: https://github.com/strangerstudios/pmpro-register-helper/commit/ab5c702f86a55f4ab8ea3cbccc0da2ea6ff09f4e

As this bug should now be fixed, I am going to close this issue. If this is a problem that you are still experiencing after updating to the most recent version of PMPro Register Helper, please feel free to create a new issue in this repository so that we can look further into this.
