### ISSUE TITLE
Sanitise file input error in main fill line 995 - undefined index.

### ISSUE THREAD

**Issue by WebbizAdmin** [strangerstudios/pmpro-register-helper#122]
RESOLVED WITH THIS CODE.

There is an error when you add file input to the PMP. It tries to sanitise the $_POST for the file ID but should sanities the $_FILE or ignore it. 

line 995 pmpro-register-helper/pmpro-register-helper.php 
added this and resolved issue.
~~~~
if(isset($_POST[$field->name])) {
	$value = pmprorh_sanitize( $_POST[ $field->name ] );
}
if(isset($_FILE[$field->name])) {
	$value = pmprorh_sanitize( $_FILE[ $field->name ] );
}
~~~~

**Comment by andrewlimaza** [comment]
Above this code, we check to see if we need to sanitize the fields in question. Can you elaborate a bit more what was the exact issue you are facing here?

**Comment by dparker1005** [comment]
Since we have not heard back from you about this issue, we are going to close this ticket. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a> and we would be happy to help.
