### ISSUE TITLE
Select values appends select's label text if set to integer only value.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-register-helper#133]
If you set the code to:
`'select',
    array(
      'options' => array(
        '1' => 'Label 1',
        '2' => 'Label 2',
        '3' => 'Label 3',
        '4' => 'Label 4',
      ),
`

The field output looks like:

`
option value="Label 1"
option value="Label 2"
option value="Label 3"
option value="Label 4"
`

**Comment by tbnv** [comment]
Hello.

Any news about this issue?

**Comment by tbnv** [comment]
Hello.

Problem reported and issue opened 2 months ago.
Do you have any update about this?

**Comment by andrewlimaza** [comment]
Hi @tbnv 

Unfortunately I do not have an exact date when this issue will be resolved. If you need to fix this urgently, please feel free to reach out to a developer (here's a link to <a href="https://www.paidmembershipspro.com/developers">partner developers</a> for PMPro). If you are familiar with code, we do accept Pull Requests and encourage them as it helps speed up development.

Thank you for understanding.

**Comment by andrewlimaza** [comment]
I think a workaround would be to do something like:

`
'select', array( 'options' => array( 'please_select' => 'Select an option', '1' => 'Label 1', '2' => 'Label 2', '3' => 'Label 3', '4' => 'Label 4', ),
`

**Comment by ajfick** [comment]
I'm having the same issue. Also, the select field in my case needs to be required, so I imagine adding a `please_select` option would essentially break that as a user leaving the value unchanged would qualify as them making a selection.

**Comment by dparker1005** [comment]
After looking into this issue, this behavior appears to be caused by code that repairs non-associative arrays that are passed in as parameters to the `options` setting of `select` fields:
https://github.com/strangerstudios/pmpro-register-helper/blob/e70508f8f7a924f7606949e80097953e5ad27398/classes/class.field.php#L113-L120

You can disable this behavior by adding the following line of PHP to your site:
`add_action('pmprorh_repair_non_associative_options', '__return_false');`
