### ISSUE TITLE
Extra field required also if inserted from User profile

### ISSUE THREAD

**Issue by antoroxx** [strangerstudios/pmpro-register-helper#14]
I installed Paid Membership, pmpro-register-helper and pmpro-customizations, created a required extra-field "company". I always get the following issue:
If I create a user in the Wordpress backend, from the "User" section and i fill the required extra-field "company" there, when I try to register to a Membership level from a post part of it, I always get an alert:
 "The company fields are required." and I can't proceed in the Level registration.
May be it'll never happen that I should create a user from the backend but this mean that something doesn't work with the database....
Please it's urgent, let me know!!
Many thanx
Antonio

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported which should have fixed this behavior. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
