### ISSUE TITLE
Change Textarea Sanitzation in order to Retain Safe HTML in User Input

### ISSUE THREAD

**Issue by VR51** [strangerstudios/pmpro-register-helper#217]
Sometimes we need to keep the HTML that is entered into textarea fields but Register Helper strips HTML tags when profile data are saved.

On reading the plugin code I can see an undocumented ‘sanitize’ option. Setting ``sanitize => false`` removes text sanitization so HTML remains in place.

However, lack of data sanitization signals ‘come and get me’ to hackers.

An alternative approach to sanitazation of textareas would be to change line 574 of file ``pmpro-register-helper.php`` to replace ``sanitize_textarea_field()`` with ``wp_filter_kses()``, which retains basic HTML tags when data is saved.

The current code block looks like this (starting at line 573):

```if ( ! empty( $field ) && ! empty( $field->type ) && $field->type === 'textarea' ) {
$value = sanitize_textarea_field( $value );
} elseif ( ( ! is_array( $value ) ) && ctype_alpha( $value ) ||
	   ( ( ! is_array( $value ) ) && strtotime( $value ) ) ||
	   ( ( ! is_array( $value ) ) && is_string( $value ) ) ||
	   ( ( ! is_array( $value ) ) && is_numeric( $value) )
) {

$value = sanitize_text_field( $value );
}
```

The improved version looks like this:

```if ( ! empty( $field ) && ! empty( $field->type ) && $field->type === 'textarea' ) {
$value = wp_filter_kses( $value );
} elseif ( ( ! is_array( $value ) ) && ctype_alpha( $value ) ||
	   ( ( ! is_array( $value ) ) && strtotime( $value ) ) ||
	   ( ( ! is_array( $value ) ) && is_string( $value ) ) ||
	   ( ( ! is_array( $value ) ) && is_numeric( $value) )
) {

$value = sanitize_text_field( $value );
}
```

Another approach would be to expand the options to include a lightsanitize option where ``lightsanitize => true`` would switch ``sanitize_text_field()`` to ``wp_filter_kses()``.

What are your thoughts?

**Comment by ideadude** [comment]
Hi, Lee. Thanks for the feedback here. I agree, it would be nice to be able to override the sanitization function so you can save HTML in fields or similarly lighten up the sanitization when needed.

An idea we had before that we can work on is to check if the ->sanitize value is a string, and if so, assume it's a function and use that function to sanitize the value instead of the default.

I'm currently working on merging the Register Helper plugin into the core PMPro and may add that feature to the work there or add an issue on the core PMPro repo about this if I don't get to it.

A similar thing you could do now that I think should work for your need is to override the "save_function" option on the field. If you set the save_function option to the name of a different callback function, that will be used to save the field value... and you can add your own sanitization in there. So a combo of sanitize = false, then a custom save_function could work.

Here is an example of that: https://gist.github.com/ipokkel/e34215c3517bf89467f90428b7364aa0

**Comment by VR51** [comment]
Thank you very much @ideadude. I like the ideas used in the Gist. I shall probably go with that method in the interim until a stable method for this feature is added to Register Helper/PMPro  itself. This will be less nerve wracking than watching for the next plugin update (forgetting) to re-edit the code for textarea fields.

About an additional item, I forked the Import Users from CSV plugin to add an import schedule option. I will issue a pull request when I've made a few more edits to it. The fork is here https://github.com/VR51/import-users-from-csv
