### ISSUE TITLE
Asterisk and Validation Error for Required Fields

### ISSUE THREAD

**Issue by mcs2k1** [strangerstudios/pmpro-register-helper#3]
Fields that are set to required doesn't show the asterisk and doesn't highlight (red) after submitting if left blank.

**Comment by netmaxims** [comment]
sas

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported which should have fixed this behavior. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
