### ISSUE TITLE
Required Fields create problems with renewal

### ISSUE THREAD

**Issue by whitsey** [strangerstudios/pmpro-register-helper#33]
After adding required extra fields to the registration page, any existing subscribers who registered prior to the fields being added and who have not completed the new mandatory fields cannot renew their membership.

See attached message that is displayed.

The extra registration fields do not display when the user is logged in, therefore they are not prompted to update the required fields...

![screen shot 2014-07-11 at 10 22 44 am](https://cloud.githubusercontent.com/assets/3803274/3547321/b77bd79a-0894-11e4-8e91-3848b270c4e5.png)

**Comment by dparker1005** [comment]
Since we have not heard back from you about this issue, we are going to close this ticket. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
