### ISSUE TITLE
Adding New field not working

### ISSUE THREAD

**Issue by dhirnitish** [strangerstudios/pmpro-register-helper#46]
I have added this function to my theme functions.php file

add_action('pmpro_checkout_after_billing_fields','add_fields_pmpro_merchant');  
function add_fields_pmpro_merchant(){
    $field = new PMProRH_Field("company", "text", array("size"=>40, "required"=>true));
    pmprorh_add_registration_field("business", $field);
}

But i am not able to see any new field on my registration form

**Comment by dhirnitish** [comment]
Also i would like to know why i need to do this 
Add a sign up form to a post/widget/page using a shortcode:

[pmpro_signup level="3" short="1" intro="0" button="Signup Now"]

Because the urls work in a different way
membership-account/membership-checkout/?level=2

**Comment by dparker1005** [comment]
Hello @dhirnitish,

Looking at the code from your original post, I would recommend changing the function to hook on `init` instead of `pmpro_checkout_after_billing_fields` to ensure that the field is set to be added when the checkout form is being generated. Also, if you wanted to add this field to a new "business" checkout box, it would be necessary to also have the following line of code in the beginning of your function to create that checkout box: `pmprorh_add_checkout_box("business", "Business Information");`

The resulting code should look something like:
```
function add_fields_pmpro_merchant() {
        pmprorh_add_checkout_box("business", "Business Information");
        $field = new PMProRH_Field("company", "text", array("size"=>40, "required"=>true));
        pmprorh_add_registration_field("business", $field);
}
add_action('init', 'add_fields_pmpro_merchant');
```

Regarding your question about the `[pmpro_signup]` shortcode, it is not necessary to use that functionality on your site; however, it is useful if you would like to give users a convenient way to sign up from any page on your site. If you run into any issues while using that shortcode, please open a new issue in that Add On's GitHub repository here: https://github.com/strangerstudios/pmpro-signup-shortcode

I hope the above code helps to get you started. If you have further support questions about how to use this Add On, please <a href="https://www.paidmembershipspro.com/new-topic/">open a new ticket in the PMPro Support Forum</a> and we would be happy to help you in more detail there.
