### ISSUE TITLE
Date field is not working

### ISSUE THREAD

**Issue by wpmix** [strangerstudios/pmpro-register-helper#48]
Date field is not working

Warning: strtotime() expects parameter 1 to be string, array given in => \wp-content\plugins\pmpro-register-helper\classes\class.field.php on line 423

**Comment by strangerstudios** [comment]
We might be able to force cast $value at that line to a string to avoid this warning, but I think the fact that you are getting that might be due to something else on your site storing an array in the same usermeta key. Or maybe you switched the field type of a field from something stored in an array (multiselects and files) to a date type.

Let me know if this makes sense.

**Comment by dparker1005** [comment]
PMPro Register Helper v1.3.4 contains a commit here which should have resolved this warning:
https://github.com/strangerstudios/pmpro-register-helper/commit/6bbc6851d4c168bee113dbe155fcc161f397018f

As this warning should now be resolved, I am going to close this issue. If this is a problem that you are still experiencing after updating to the most recent version of PMPro Register Helper, please feel free to create a new issue in this repository so that we can look further into this.
