### ISSUE TITLE
"levels" attribute only accepts array

### ISSUE THREAD

**Issue by andyschaff** [strangerstudios/pmpro-register-helper#49]
Just wanted to inform you that the documentation states that the "levels" option accepts an int or array, but only the array definition is working. I tried with "levels"=>2 and it did not work.

Got it working with an array:

$fields[] = new PMProRH_Field(
        "studentname",                  // input name, will also be used as meta key
        "text",                         // type of field
        array(
            "label"=>"Student Name",    // custom field label
            "size"=>30,                 // input size
            "profile"=>true,            // show in user profile ("admins" for admins only)
            "required"=>true,           // make this field required
            "levels"=>array(2),         // levels to show this for. 2 = student
            "memberslistcsv"=>true      // show on export csv
        ));

**Comment by strangerstudios** [comment]
Fix for this going out today. Thanks.

**Comment by andyschaff** [comment]
Hey Jason,

Hate to say this, but now the array() functionality does not work for "levels". 
I had to update my code to use "levels"=>2 in order for it to work properly.

**Comment by dparker1005** [comment]
Hi @andyschaff,

There was an commit released in PMPro Register Helper v1.2 that should have addressed this issue: https://github.com/strangerstudios/pmpro-register-helper/commit/1454a2c2a760371d98954df378cc3fb958681fec

As this behavior should now be fixed, I am going to close this issue. If this is a problem that you are still experiencing after updating to the most recent version of PMPro Register Helper, please feel free to create a new issue in this repository so that we can look further into this.
