### ISSUE TITLE
Whitelisting IP's?

### ISSUE THREAD

**Issue by Petronell** [strangerstudios/pmpro-register-helper#56]
Do you have a list of IP addresses that my host should whitelist perhaps?

**Comment by dparker1005** [comment]
Hi @Petronell,

PMPro usually does not require any specific IP's to be whitelisted in order to function. One potential exception to this rule is if your payment gateway (PayPal, Stripe, etc) is being blocked from accessing your IPN/Webhook URL, in which case you should contact your host to ask them to allow your payment gateway to access that URL.

As this does not seem directly related to PMPro Register Helper, I am going to close this issue, but please feel free to <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a> if you have questions about whether it is necessary to whitelist any specific IP's that you have in mind.
