### ISSUE TITLE
strtotime() expects parameter 1 to be string in class.field.php on line 444

### ISSUE THREAD

**Issue by bburgay** [strangerstudios/pmpro-register-helper#62]
I'm getting Warning:  strtotime() expects parameter 1 to be string, array given in .....pmpro-register-helper\classes\class.field.php on line 444 (//setup date vars).

Please add a check "... && is_string($value)" on line 443.

**Comment by dparker1005** [comment]
Hi @bburgay,

There was an commit released in PMPro Register Helper v1.2 that should have addressed this issue: https://github.com/strangerstudios/pmpro-register-helper/commit/1454a2c2a760371d98954df378cc3fb958681fec

As this behavior should now be fixed, I am going to close this issue. If this is a problem that you are still experiencing after updating to the most recent version of PMPro Register Helper, please feel free to create a new issue in this repository so that we can look further into this.
