### ISSUE TITLE
Error generated with TML themed profiles activated

### ISSUE THREAD

**Issue by bridieamelia** [strangerstudios/pmpro-register-helper#65]
Error message: 

> Notice: Trying to get property of non-object in /home/iaminfin/public_html/wp-content/plugins/pmpro-register-helper-master/pmpro-register-helper.php on line 668

Fix: change line 668 from
`<h3><?php echo $box->label;?></h3>`
to
`<h3><?php echo isset($box->label) ? $box->label : '';?></h3>`

Cheers

**Comment by bridieamelia** [comment]
Maybe this is supposed to be in pull requests?

**Comment by dparker1005** [comment]
Hi @bridieamelia,

Thank you for reporting this behavior. There was a commit pushed out in PMPro Register Helper v1.3 which should have resolved this notice: https://github.com/strangerstudios/pmpro-register-helper/commit/6574cb4221b0266b88596dde1dfc27b0eedbc14b

As this notice should now be resolved, I am going to close this issue. If this is a problem that you are still experiencing after updating to the most recent version of PMPro Register Helper, please feel free to create a new issue in this repository so that we can look further into this.
