### ISSUE TITLE
HTML Field without label

### ISSUE THREAD

**Issue by barryross** [strangerstudios/pmpro-register-helper#8]
Hi there, is it possible to create an html field but not have the label appear?

**Comment by dparker1005** [comment]
Since version `.5.2`, you can now pass `false` for the `"label"` variable to prevent the label from being shown. For more information, please see the row in the "options" table for "label" here: https://www.paidmembershipspro.com/documentation/register-helper-documentation/adding-fields/

If you have further questions about this, please feel free to <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a> and we would be happy to help.
