### ISSUE TITLE
Multiselect in Admin

### ISSUE THREAD

**Issue by arudd20** [strangerstudios/pmpro-register-helper#9]
If a user selects one or more option(s) using the the $select2 field and saves the information, how do I know what options were saved in the admin?

The multiselect options aren't highlighted or anything like that.
Any help is appreciated.

**Comment by dparker1005** [comment]
We are closing this issue as there have been major updates since this bug was reported which should have fixed this behavior. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.
